version: "3.7"

services:
  nacos:
    image: ustc-edu-cn.mirror.aliyuncs.com/nacos/nacos-server
    container_name: nacos-standalone-mysql
    restart: unless-stopped
    env_file:
      - ./nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: ustc-edu-cn.mirror.aliyuncs.com/nacos/nacos-mysql:8.0.16
    restart: unless-stopped
    env_file:
      - ./mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db-dump:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
