server:
  shutdown: graceful
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
spring:
  datasource:
    username: ${OPENGAUSS_USERNAME:gaussdb}
    password: ${OPENGAUSS_PASSWORD:Secretpassword@123}
    url: jdbc:postgresql://${OPENGAUSS_URL:localhost}:${OPENGAUSS_PORT:5432}/${OPENGAUSS_DB:postgres}
  lifecycle:
    timeout-per-shutdown-phase: 30s
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
      date-time-zone: Asia/Shanghai
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: abcdefghijklmnopqrstuvwxyz
  expiration-delay: 86400
shopClient:
  ribbon:
    listOfServers: ${SHOP_FEIGN_URL:http://localhost:9210}
productClient:
  ribbon:
    listOfServers: ${PRODUCT_FEIGN_URL:http://localhost:9888}
customerClient:
  ribbon:
    listOfServers: ${PRODUCT_FEIGN_URL:http://localhost:9220}