server:
  shutdown: graceful
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
spring:
  datasource:
    username: ${OPENGAUSS_USERNAME:gaussdb}
    password: ${OPENGAUSS_PASSWORD:Secretpassword@123}
    url: jdbc:postgresql://${OPENGAUSS_URL:localhost}:${OPENGAUSS_PORT:5432}/${OPENGAUSS_DB:postgres}
  lifecycle:
    timeout-per-shutdown-phase: 30s
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
      date-time-zone: Asia/Shanghai
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    show-sql: true # 打开Hibernate sql语句输出
    # 以下属性可以定义在文件hibernate.properties中，然后引用在配置文件中
    properties:
      hibernate:
        ddl-auto: update
        # 要打开缓存操作详情输出，则设置为true
        generate_statistics: false
        javax:
          cache:
            missing_cache_strategy: create
        cache:
          format_sql: true
          use_second_level_cache: true # 开启二级缓存
          use_query_cache: true # 开启查询缓存
          region:
            # 使用jCache作为缓存工厂类
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          use_structured_entries: true
          provider_configuration_file_resource_path: ehcache.xml
jwt:
  secret: abcdefghijklmnopqrstuvwxyz
  expiration-delay: 86400
authClient:
  ribbon:
    listOfServers: ${AUTH_FEIGN_URL:http://localhost:9000}
commodityClient:
  ribbon:
    listOfServers: ${COMMODITY_FEIGN_URL:http://localhost:9200}
customerClient:
  ribbon:
    listOfServers: ${CUSTOMER_FEIGN_URL:http://localhost:9220}
orderClient:
  ribbon:
    listOfServers: ${ORDER_FEIGN_URL:http://localhost:9230}
shopClient:
  ribbon:
    listOfServers: ${SHOP_FEIGN_URL:http://localhost:9210}
userClient:
  ribbon:
    listOfServers: ${USER_FEIGN_URL:http://localhost:9100}
