spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            exposedHeaders: "Content-Disposition,Content-Type,Cache-Control"
      routes:
        # 授权认证模块
        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Path=/v1/auth/**
          filters:
            - StripPrefix=2
        # 用户模块
        - id: mall-user
          uri: lb://mall-user
          predicates:
            - Path=/v1/users/**
          filters:
            - StripPrefix=2
        # 商店模块
        - id: mall-shop
          uri: lb://mall-shop
          predicates:
            - Path=/shops/**
          filters:
            - StripPrefix=1
        # 商品模块
        - id: mall-commodity
          uri: lb://mall-commodity
          predicates:
            - Path=/commodities/**
          filters:
            - StripPrefix=1