FROM openjdk:11-jre
COPY wait-for-it.sh /root/wait-for-it.sh
RUN chmod +x /root/wait-for-it.sh
COPY mall-auth/target/mall-auth.jar /root/mall-auth.jar
ENTRYPOINT ["/root/wait-for-it.sh", "nacos:8848", "-t", "180", "--strict", "--", "java", "-jar", "/root/mall-auth.jar"]