name: Build Chatbot
on:
  # only run manually
  workflow_dispatch:
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build_frontend
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./backend/chatbot
          file: ./backend/chatbot/Dockerfile
          push: true
          tags: frogsoftware/mall-chatbot:latest
          builder: ${{ steps.buildx.outputs.name }}
